"""tenant closing_action

Revision ID: 846b477f0238
Revises: 67e14af30433
Create Date: 2026-07-24 01:52:04.530012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846b477f0238'
down_revision: Union[str, None] = '67e14af30433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenants',
        sa.Column(
            'closing_action',
            sa.String(),
            nullable=False,
            server_default='escalate_to_human',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'closing_action')
    # ### end Alembic commands ###
